Repository 8select/shopware-plugin-sob, pull requests merged in 2019-04, with the labels that each got.

#106 CSE-2058 api for product attributes and dimensions
  CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
  CseEightselectBasic/Resources/services.xml
  CseEightselectBasic/Services/Export/Attributes.php
  CseEightselectBasic/Services/Export/Connector.php
  CseEightselectBasic/Services/Export/RawExport.php
  CseEightselectBasic/Services/Export/VariantDimensions.php
  bin/lib/build.sh
  bin/lib/common.sh
  bin/release.sh
Labels: feature

#107 CSE-2056 return all product attributes in raw export
  CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
  CseEightselectBasic/Resources/services.xml
  CseEightselectBasic/Services/Export/Attributes.php
  CseEightselectBasic/Services/Export/Helper/Fields.php
  CseEightselectBasic/Services/Export/Helper/ProductImages.php
  CseEightselectBasic/Services/Export/RawExport.php
  CseEightselectBasic/Services/Export/RawExportMapper.php
  bin/copy2dev.sh
Labels: breaking change, feature

#108 CSE-2072 disable upgrade to 3.x
  CseEightselectBasic/CseEightselectBasic.php
Labels: feature

#109 CSE-2072 remove variant attribute config requirement
  CseEightselectBasic/Services/Config/Validator.php
  CseEightselectBasic/Setup/Install.php
  CseEightselectBasic/Setup/Uninstall.php
Labels: feature

#110 add supplier name to list of attributes
  CseEightselectBasic/Services/Export/Attributes.php
Labels: bug

#111 CSE-2072 remove deprecated components
  CseEightselectBasic/Components/Export.php
  CseEightselectBasic/Controllers/Backend/CseEightselectBasicAttributeConfig.php
  CseEightselectBasic/Controllers/Frontend/CseEightselectBasic.php
  CseEightselectBasic/CseEightselectBasic.php
  CseEightselectBasic/Resources/menu.xml
  CseEightselectBasic/Resources/services.xml
  CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_attribute_config/app.js
  CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_attribute_config/controller/main.js
  CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_attribute_config/model/eightselect_attribute.js
  CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_attribute_config/model/shopware_attribute.js
  CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_attribute_config/store/eightselect_attribute.js
  CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_attribute_config/store/shopware_attribute.js
  CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_attribute_config/view/list/eightselect_attribute.js
  CseEightselectBasic/Resources/views/backend/cse_eightselect_basic_attribute_config/view/list/window.js
  CseEightselectBasic/Services/Export/Helper/Mapper.php
  CseEightselectBasic/Setup/Helpers/AttributeMapping.php
  CseEightselectBasic/Setup/Helpers/SizeAttribute.php
  CseEightselectBasic/Setup/Install.php
  CseEightselectBasic/Setup/Uninstall.php
Labels: feature
